version: "2"
services:
  webserver:
    image: mydemophpimage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      SITE_URL: http://localhost
  mydemoreactimage:
    image: mydemoreactimage
    container_name: mydemoreactimage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend/react-docker:/app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true